language: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install more-itertools
    - pip install scipy
script:
    - py.test
after_success:
    - coveralls
    - more-itertools
notifications:
    email: false
