language: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install more-itertools
    - git lfs pull
env:
  - FILES="rxns.xml"
script:
    - py.test
after_success:
    - coveralls
    - more-itertools
